[package]
name = "rox"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "plotters"] }
pprof = { version = "0.13.0", features = ["flamegraph", "criterion"] }

[[bench]]
name = "bench_main"
harness = false
